export interface ICurrency {
  code: string;
  name: string;
  symbol: string;
}

export interface ILanguage {
  code: string;
  name: string;
}

export type Countries = {
  name: string;
  code: string;
  capital: string;
  region: string;
  currency: ICurrency;
  language: ILanguage;
  flag: string;
};

export const countries: Countries[] = [
  {
    name: "Afghanistan",
    code: "AF",
    capital: "Kabul",
    region: "Asia",
    currency: { code: "AFN", name: "Afghan afghani", symbol: "؋" },
    language: { code: "ps", name: "Pashto" },
    flag: "https://flagcdn.com/af.svg",
  },
  {
    name: "Albania",
    code: "AL",
    capital: "Tirana",
    region: "Europe",
    currency: { code: "ALL", name: "Albanian lek", symbol: "L" },
    language: { code: "sq", name: "Albanian" },
    flag: "https://flagcdn.com/al.svg",
  },
  {
    name: "Algeria",
    code: "DZ",
    capital: "Algiers",
    region: "Africa",
    currency: { code: "DZD", name: "Algerian dinar", symbol: "د.ج" },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/dz.svg",
  },
  {
    name: "Andorra",
    code: "AD",
    capital: "Andorra la Vella",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "ca", name: "Catalan" },
    flag: "https://flagcdn.com/ad.svg",
  },
  {
    name: "Angola",
    code: "AO",
    capital: "Luanda",
    region: "Africa",
    currency: { code: "AOA", name: "Angolan kwanza", symbol: "Kz" },
    language: { code: "pt", name: "Portuguese" },
    flag: "https://flagcdn.com/ao.svg",
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    capital: "Saint John's",
    region: "Americas",
    currency: { code: "XCD", name: "East Caribbean dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/ag.svg",
  },
  {
    name: "Argentina",
    code: "AR",
    capital: "Buenos Aires",
    region: "Americas",
    currency: { code: "ARS", name: "Argentine peso", symbol: "$" },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/ar.svg",
  },
  {
    name: "Armenia",
    code: "AM",
    capital: "Yerevan",
    region: "Asia",
    currency: { code: "AMD", name: "Armenian dram", symbol: "֏" },
    language: { code: "hy", name: "Armenian" },
    flag: "https://flagcdn.com/am.svg",
  },
  {
    name: "Australia",
    code: "AU",
    capital: "Canberra",
    region: "Oceania",
    currency: { code: "AUD", name: "Australian dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/au.svg",
  },
  {
    name: "Austria",
    code: "AT",
    capital: "Vienna",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "de", name: "German" },
    flag: "https://flagcdn.com/at.svg",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    capital: "Baku",
    region: "Asia",
    currency: { code: "AZN", name: "Azerbaijani manat", symbol: "₼" },
    language: { code: "az", name: "Azerbaijani" },
    flag: "https://flagcdn.com/az.svg",
  },
  {
    name: "Bahamas",
    code: "BS",
    capital: "Nassau",
    region: "Americas",
    currency: { code: "BSD", name: "Bahamian dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/bs.svg",
  },
  {
    name: "Bahrain",
    code: "BH",
    capital: "Manama",
    region: "Asia",
    currency: { code: "BHD", name: "Bahraini dinar", symbol: ".د.ب" },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/bh.svg",
  },
  {
    name: "Bangladesh",
    code: "BD",
    capital: "Dhaka",
    region: "Asia",
    currency: { code: "BDT", name: "Bangladeshi taka", symbol: "৳" },
    language: { code: "bn", name: "Bengali" },
    flag: "https://flagcdn.com/bd.svg",
  },
  {
    name: "Barbados",
    code: "BB",
    capital: "Bridgetown",
    region: "Americas",
    currency: { code: "BBD", name: "Barbadian dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/bb.svg",
  },
  {
    name: "Belarus",
    code: "BY",
    capital: "Minsk",
    region: "Europe",
    currency: { code: "BYN", name: "Belarusian ruble", symbol: "Br" },
    language: { code: "be", name: "Belarusian" },
    flag: "https://flagcdn.com/by.svg",
  },
  {
    name: "Belgium",
    code: "BE",
    capital: "Brussels",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "nl", name: "Dutch" },
    flag: "https://flagcdn.com/be.svg",
  },
  {
    name: "Belize",
    code: "BZ",
    capital: "Belmopan",
    region: "Americas",
    currency: { code: "BZD", name: "Belize dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/bz.svg",
  },
  {
    name: "Benin",
    code: "BJ",
    capital: "Porto-Novo",
    region: "Africa",
    currency: { code: "XOF", name: "West African CFA franc", symbol: "Fr" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/bj.svg",
  },
  {
    name: "Bhutan",
    code: "BT",
    capital: "Thimphu",
    region: "Asia",
    currency: { code: "BTN", name: "Bhutanese ngultrum", symbol: "Nu." },
    language: { code: "dz", name: "Dzongkha" },
    flag: "https://flagcdn.com/bt.svg",
  },
  {
    name: "Bolivia",
    code: "BO",
    capital: "Sucre",
    region: "Americas",
    currency: { code: "BOB", name: "Bolivian boliviano", symbol: "Bs." },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/bo.svg",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    capital: "Sarajevo",
    region: "Europe",
    currency: {
      code: "BAM",
      name: "Bosnia and Herzegovina convertible mark",
      symbol: "KM",
    },
    language: { code: "bs", name: "Bosnian" },
    flag: "https://flagcdn.com/ba.svg",
  },
  {
    name: "Botswana",
    code: "BW",
    capital: "Gaborone",
    region: "Africa",
    currency: { code: "BWP", name: "Botswana pula", symbol: "P" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/bw.svg",
  },
  {
    name: "Brazil",
    code: "BR",
    capital: "Brasília",
    region: "Americas",
    currency: { code: "BRL", name: "Brazilian real", symbol: "R$" },
    language: { code: "pt", name: "Portuguese" },
    flag: "https://flagcdn.com/br.svg",
  },
  {
    name: "Brunei",
    code: "BN",
    capital: "Bandar Seri Begawan",
    region: "Asia",
    currency: { code: "BND", name: "Brunei dollar", symbol: "$" },
    language: { code: "ms", name: "Malay" },
    flag: "https://flagcdn.com/bn.svg",
  },
  {
    name: "Bulgaria",
    code: "BG",
    capital: "Sofia",
    region: "Europe",
    currency: { code: "BGN", name: "Bulgarian lev", symbol: "лв" },
    language: { code: "bg", name: "Bulgarian" },
    flag: "https://flagcdn.com/bg.svg",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    capital: "Ouagadougou",
    region: "Africa",
    currency: { code: "XOF", name: "West African CFA franc", symbol: "Fr" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/bf.svg",
  },
  {
    name: "Burundi",
    code: "BI",
    capital: "Gitega",
    region: "Africa",
    currency: { code: "BIF", name: "Burundian franc", symbol: "Fr" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/bi.svg",
  },
  {
    name: "Cambodia",
    code: "KH",
    capital: "Phnom Penh",
    region: "Asia",
    currency: { code: "KHR", name: "Cambodian riel", symbol: "៛" },
    language: { code: "km", name: "Khmer" },
    flag: "https://flagcdn.com/kh.svg",
  },
  {
    name: "Cameroon",
    code: "CM",
    capital: "Yaoundé",
    region: "Africa",
    currency: { code: "XAF", name: "Central African CFA franc", symbol: "Fr" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/cm.svg",
  },
  {
    name: "Canada",
    code: "CA",
    capital: "Ottawa",
    region: "Americas",
    currency: { code: "CAD", name: "Canadian dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/ca.svg",
  },
  {
    name: "Cape Verde",
    code: "CV",
    capital: "Praia",
    region: "Africa",
    currency: { code: "CVE", name: "Cape Verdean escudo", symbol: "$" },
    language: { code: "pt", name: "Portuguese" },
    flag: "https://flagcdn.com/cv.svg",
  },
  {
    name: "Central African Republic",
    code: "CF",
    capital: "Bangui",
    region: "Africa",
    currency: { code: "XAF", name: "Central African CFA franc", symbol: "Fr" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/cf.svg",
  },
  {
    name: "Chad",
    code: "TD",
    capital: "N'Djamena",
    region: "Africa",
    currency: { code: "XAF", name: "Central African CFA franc", symbol: "Fr" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/td.svg",
  },
  {
    name: "Chile",
    code: "CL",
    capital: "Santiago",
    region: "Americas",
    currency: { code: "CLP", name: "Chilean peso", symbol: "$" },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/cl.svg",
  },
  {
    name: "China",
    code: "CN",
    capital: "Beijing",
    region: "Asia",
    currency: { code: "CNY", name: "Chinese yuan", symbol: "¥" },
    language: { code: "zh", name: "Chinese" },
    flag: "https://flagcdn.com/cn.svg",
  },
  {
    name: "Colombia",
    code: "CO",
    capital: "Bogotá",
    region: "Americas",
    currency: { code: "COP", name: "Colombian peso", symbol: "$" },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/co.svg",
  },
  {
    name: "Comoros",
    code: "KM",
    capital: "Moroni",
    region: "Africa",
    currency: { code: "KMF", name: "Comorian franc", symbol: "Fr" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/km.svg",
  },
  {
    name: "Costa Rica",
    code: "CR",
    capital: "San José",
    region: "Americas",
    currency: { code: "CRC", name: "Costa Rican colón", symbol: "₡" },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/cr.svg",
  },
  {
    name: "Croatia",
    code: "HR",
    capital: "Zagreb",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "hr", name: "Croatian" },
    flag: "https://flagcdn.com/hr.svg",
  },
  {
    name: "Cuba",
    code: "CU",
    capital: "Havana",
    region: "Americas",
    currency: { code: "CUP", name: "Cuban peso", symbol: "$" },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/cu.svg",
  },
  {
    name: "Cyprus",
    code: "CY",
    capital: "Nicosia",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "el", name: "Greek" },
    flag: "https://flagcdn.com/cy.svg",
  },
  {
    name: "Czech Republic",
    code: "CZ",
    capital: "Prague",
    region: "Europe",
    currency: { code: "CZK", name: "Czech koruna", symbol: "Kč" },
    language: { code: "cs", name: "Czech" },
    flag: "https://flagcdn.com/cz.svg",
  },
  {
    name: "Democratic Republic of the Congo",
    code: "CD",
    capital: "Kinshasa",
    region: "Africa",
    currency: { code: "CDF", name: "Congolese franc", symbol: "Fr" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/cd.svg",
  },
  {
    name: "Denmark",
    code: "DK",
    capital: "Copenhagen",
    region: "Europe",
    currency: { code: "DKK", name: "Danish krone", symbol: "kr" },
    language: { code: "da", name: "Danish" },
    flag: "https://flagcdn.com/dk.svg",
  },
  {
    name: "Djibouti",
    code: "DJ",
    capital: "Djibouti",
    region: "Africa",
    currency: { code: "DJF", name: "Djiboutian franc", symbol: "Fr" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/dj.svg",
  },
  {
    name: "Dominica",
    code: "DM",
    capital: "Roseau",
    region: "Americas",
    currency: { code: "XCD", name: "East Caribbean dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/dm.svg",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    capital: "Santo Domingo",
    region: "Americas",
    currency: { code: "DOP", name: "Dominican peso", symbol: "$" },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/do.svg",
  },
  {
    name: "East Timor",
    code: "TL",
    capital: "Dili",
    region: "Asia",
    currency: { code: "USD", name: "United States dollar", symbol: "$" },
    language: { code: "pt", name: "Portuguese" },
    flag: "https://flagcdn.com/tl.svg",
  },
  {
    name: "Ecuador",
    code: "EC",
    capital: "Quito",
    region: "Americas",
    currency: { code: "USD", name: "United States dollar", symbol: "$" },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/ec.svg",
  },
  {
    name: "Egypt",
    code: "EG",
    capital: "Cairo",
    region: "Africa",
    currency: { code: "EGP", name: "Egyptian pound", symbol: "£" },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/eg.svg",
  },
  {
    name: "El Salvador",
    code: "SV",
    capital: "San Salvador",
    region: "Americas",
    currency: { code: "USD", name: "United States dollar", symbol: "$" },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/sv.svg",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    capital: "Malabo",
    region: "Africa",
    currency: { code: "XAF", name: "Central African CFA franc", symbol: "Fr" },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/gq.svg",
  },
  {
    name: "Eritrea",
    code: "ER",
    capital: "Asmara",
    region: "Africa",
    currency: { code: "ERN", name: "Eritrean nakfa", symbol: "Nfk" },
    language: { code: "ti", name: "Tigrinya" },
    flag: "https://flagcdn.com/er.svg",
  },
  {
    name: "Estonia",
    code: "EE",
    capital: "Tallinn",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "et", name: "Estonian" },
    flag: "https://flagcdn.com/ee.svg",
  },
  {
    name: "Eswatini",
    code: "SZ",
    capital: "Mbabane",
    region: "Africa",
    currency: { code: "SZL", name: "Swazi lilangeni", symbol: "L" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/sz.svg",
  },
  {
    name: "Ethiopia",
    code: "ET",
    capital: "Addis Ababa",
    region: "Africa",
    currency: { code: "ETB", name: "Ethiopian birr", symbol: "Br" },
    language: { code: "am", name: "Amharic" },
    flag: "https://flagcdn.com/et.svg",
  },
  {
    name: "Fiji",
    code: "FJ",
    capital: "Suva",
    region: "Oceania",
    currency: { code: "FJD", name: "Fijian dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/fj.svg",
  },
  {
    name: "Finland",
    code: "FI",
    capital: "Helsinki",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "fi", name: "Finnish" },
    flag: "https://flagcdn.com/fi.svg",
  },
  {
    name: "France",
    code: "FR",
    capital: "Paris",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/fr.svg",
  },
  {
    name: "Gabon",
    code: "GA",
    capital: "Libreville",
    region: "Africa",
    currency: { code: "XAF", name: "Central African CFA franc", symbol: "Fr" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/ga.svg",
  },
  {
    name: "Gambia",
    code: "GM",
    capital: "Banjul",
    region: "Africa",
    currency: { code: "GMD", name: "Gambian dalasi", symbol: "D" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/gm.svg",
  },
  {
    name: "Georgia",
    code: "GE",
    capital: "Tbilisi",
    region: "Asia",
    currency: { code: "GEL", name: "Georgian lari", symbol: "₾" },
    language: { code: "ka", name: "Georgian" },
    flag: "https://flagcdn.com/ge.svg",
  },
  {
    name: "Germany",
    code: "DE",
    capital: "Berlin",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "de", name: "German" },
    flag: "https://flagcdn.com/de.svg",
  },
  {
    name: "Ghana",
    code: "GH",
    capital: "Accra",
    region: "Africa",
    currency: { code: "GHS", name: "Ghanaian cedi", symbol: "₵" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/gh.svg",
  },
  {
    name: "Greece",
    code: "GR",
    capital: "Athens",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "el", name: "Greek" },
    flag: "https://flagcdn.com/gr.svg",
  },
  {
    name: "Grenada",
    code: "GD",
    capital: "St. George's",
    region: "Americas",
    currency: { code: "XCD", name: "East Caribbean dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/gd.svg",
  },
  {
    name: "Guatemala",
    code: "GT",
    capital: "Guatemala City",
    region: "Americas",
    currency: { code: "GTQ", name: "Guatemalan quetzal", symbol: "Q" },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/gt.svg",
  },
  {
    name: "Guinea",
    code: "GN",
    capital: "Conakry",
    region: "Africa",
    currency: { code: "GNF", name: "Guinean franc", symbol: "Fr" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/gn.svg",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    capital: "Bissau",
    region: "Africa",
    currency: { code: "XOF", name: "West African CFA franc", symbol: "Fr" },
    language: { code: "pt", name: "Portuguese" },
    flag: "https://flagcdn.com/gw.svg",
  },
  {
    name: "Guyana",
    code: "GY",
    capital: "Georgetown",
    region: "Americas",
    currency: { code: "GYD", name: "Guyanese dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/gy.svg",
  },
  {
    name: "Haiti",
    code: "HT",
    capital: "Port-au-Prince",
    region: "Americas",
    currency: { code: "HTG", name: "Haitian gourde", symbol: "G" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/ht.svg",
  },
  {
    name: "Honduras",
    code: "HN",
    capital: "Tegucigalpa",
    region: "Americas",
    currency: { code: "HNL", name: "Honduran lempira", symbol: "L" },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/hn.svg",
  },
  {
    name: "Hungary",
    code: "HU",
    capital: "Budapest",
    region: "Europe",
    currency: { code: "HUF", name: "Hungarian forint", symbol: "Ft" },
    language: { code: "hu", name: "Hungarian" },
    flag: "https://flagcdn.com/hu.svg",
  },
  {
    name: "Iceland",
    code: "IS",
    capital: "Reykjavik",
    region: "Europe",
    currency: { code: "ISK", name: "Icelandic króna", symbol: "kr" },
    language: { code: "is", name: "Icelandic" },
    flag: "https://flagcdn.com/is.svg",
  },
  {
    name: "India",
    code: "IN",
    capital: "New Delhi",
    region: "Asia",
    currency: { code: "INR", name: "Indian rupee", symbol: "₹" },
    language: { code: "hi", name: "Hindi" },
    flag: "https://flagcdn.com/in.svg",
  },
  {
    name: "Indonesia",
    code: "ID",
    capital: "Jakarta",
    region: "Asia",
    currency: { code: "IDR", name: "Indonesian rupiah", symbol: "Rp" },
    language: { code: "id", name: "Indonesian" },
    flag: "https://flagcdn.com/id.svg",
  },
  {
    name: "Iran",
    code: "IR",
    capital: "Tehran",
    region: "Asia",
    currency: { code: "IRR", name: "Iranian rial", symbol: "﷼" },
    language: { code: "fa", name: "Persian" },
    flag: "https://flagcdn.com/ir.svg",
  },
  {
    name: "Iraq",
    code: "IQ",
    capital: "Baghdad",
    region: "Asia",
    currency: { code: "IQD", name: "Iraqi dinar", symbol: "ع.د" },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/iq.svg",
  },
  {
    name: "Ireland",
    code: "IE",
    capital: "Dublin",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "ga", name: "Irish" },
    flag: "https://flagcdn.com/ie.svg",
  },
  {
    name: "Israel",
    code: "IL",
    capital: "Jerusalem",
    region: "Asia",
    currency: { code: "ILS", name: "Israeli new shekel", symbol: "₪" },
    language: { code: "he", name: "Hebrew" },
    flag: "https://flagcdn.com/il.svg",
  },
  {
    name: "Italy",
    code: "IT",
    capital: "Rome",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "it", name: "Italian" },
    flag: "https://flagcdn.com/it.svg",
  },
  {
    name: "Jamaica",
    code: "JM",
    capital: "Kingston",
    region: "Americas",
    currency: { code: "JMD", name: "Jamaican dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/jm.svg",
  },
  {
    name: "Japan",
    code: "JP",
    capital: "Tokyo",
    region: "Asia",
    currency: { code: "JPY", name: "Japanese yen", symbol: "¥" },
    language: { code: "ja", name: "Japanese" },
    flag: "https://flagcdn.com/jp.svg",
  },
  {
    name: "Jordan",
    code: "JO",
    capital: "Amman",
    region: "Asia",
    currency: { code: "JOD", name: "Jordanian dinar", symbol: "د.ا" },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/jo.svg",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    capital: "Nur-Sultan",
    region: "Asia",
    currency: { code: "KZT", name: "Kazakhstani tenge", symbol: "₸" },
    language: { code: "kk", name: "Kazakh" },
    flag: "https://flagcdn.com/kz.svg",
  },
  {
    name: "Kenya",
    code: "KE",
    capital: "Nairobi",
    region: "Africa",
    currency: { code: "KES", name: "Kenyan shilling", symbol: "Sh" },
    language: { code: "sw", name: "Swahili" },
    flag: "https://flagcdn.com/ke.svg",
  },
  {
    name: "Kiribati",
    code: "KI",
    capital: "South Tarawa",
    region: "Oceania",
    currency: { code: "AUD", name: "Australian dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/ki.svg",
  },
  {
    name: "Kuwait",
    code: "KW",
    capital: "Kuwait City",
    region: "Asia",
    currency: { code: "KWD", name: "Kuwaiti dinar", symbol: "د.ك" },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/kw.svg",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    capital: "Bishkek",
    region: "Asia",
    currency: { code: "KGS", name: "Kyrgyzstani som", symbol: "с" },
    language: { code: "ky", name: "Kyrgyz" },
    flag: "https://flagcdn.com/kg.svg",
  },
  {
    name: "Laos",
    code: "LA",
    capital: "Vientiane",
    region: "Asia",
    currency: { code: "LAK", name: "Lao kip", symbol: "₭" },
    language: { code: "lo", name: "Lao" },
    flag: "https://flagcdn.com/la.svg",
  },
  {
    name: "Latvia",
    code: "LV",
    capital: "Riga",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "lv", name: "Latvian" },
    flag: "https://flagcdn.com/lv.svg",
  },
  {
    name: "Lebanon",
    code: "LB",
    capital: "Beirut",
    region: "Asia",
    currency: { code: "LBP", name: "Lebanese pound", symbol: "ل.ل" },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/lb.svg",
  },
  {
    name: "Lesotho",
    code: "LS",
    capital: "Maseru",
    region: "Africa",
    currency: { code: "LSL", name: "Lesotho loti", symbol: "L" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/ls.svg",
  },
  {
    name: "Liberia",
    code: "LR",
    capital: "Monrovia",
    region: "Africa",
    currency: { code: "LRD", name: "Liberian dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/lr.svg",
  },
  {
    name: "Libya",
    code: "LY",
    capital: "Tripoli",
    region: "Africa",
    currency: { code: "LYD", name: "Libyan dinar", symbol: "ل.د" },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/ly.svg",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    capital: "Vaduz",
    region: "Europe",
    currency: { code: "CHF", name: "Swiss franc", symbol: "Fr" },
    language: { code: "de", name: "German" },
    flag: "https://flagcdn.com/li.svg",
  },
  {
    name: "Lithuania",
    code: "LT",
    capital: "Vilnius",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "lt", name: "Lithuanian" },
    flag: "https://flagcdn.com/lt.svg",
  },
  {
    name: "Luxembourg",
    code: "LU",
    capital: "Luxembourg",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/lu.svg",
  },
  {
    name: "Madagascar",
    code: "MG",
    capital: "Antananarivo",
    region: "Africa",
    currency: { code: "MGA", name: "Malagasy ariary", symbol: "Ar" },
    language: { code: "mg", name: "Malagasy" },
    flag: "https://flagcdn.com/mg.svg",
  },
  {
    name: "Malawi",
    code: "MW",
    capital: "Lilongwe",
    region: "Africa",
    currency: { code: "MWK", name: "Malawian kwacha", symbol: "MK" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/mw.svg",
  },
  {
    name: "Malaysia",
    code: "MY",
    capital: "Kuala Lumpur",
    region: "Asia",
    currency: { code: "MYR", name: "Malaysian ringgit", symbol: "RM" },
    language: { code: "ms", name: "Malay" },
    flag: "https://flagcdn.com/my.svg",
  },
  {
    name: "Maldives",
    code: "MV",
    capital: "Malé",
    region: "Asia",
    currency: { code: "MVR", name: "Maldivian rufiyaa", symbol: "Rf" },
    language: { code: "dv", name: "Dhivehi" },
    flag: "https://flagcdn.com/mv.svg",
  },
  {
    name: "Mali",
    code: "ML",
    capital: "Bamako",
    region: "Africa",
    currency: { code: "XOF", name: "West African CFA franc", symbol: "Fr" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/ml.svg",
  },
  {
    name: "Malta",
    code: "MT",
    capital: "Valletta",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "mt", name: "Maltese" },
    flag: "https://flagcdn.com/mt.svg",
  },
  {
    name: "Marshall Islands",
    code: "MH",
    capital: "Majuro",
    region: "Oceania",
    currency: { code: "USD", name: "United States dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/mh.svg",
  },
  {
    name: "Mauritania",
    code: "MR",
    capital: "Nouakchott",
    region: "Africa",
    currency: { code: "MRU", name: "Mauritanian ouguiya", symbol: "UM" },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/mr.svg",
  },
  {
    name: "Mauritius",
    code: "MU",
    capital: "Port Louis",
    region: "Africa",
    currency: { code: "MUR", name: "Mauritian rupee", symbol: "₨" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/mu.svg",
  },
  {
    name: "Mexico",
    code: "MX",
    capital: "Mexico City",
    region: "Americas",
    currency: { code: "MXN", name: "Mexican peso", symbol: "$" },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/mx.svg",
  },
  {
    name: "Micronesia",
    code: "FM",
    capital: "Palikir",
    region: "Oceania",
    currency: { code: "USD", name: "United States dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/fm.svg",
  },
  {
    name: "Moldova",
    code: "MD",
    capital: "Chișinău",
    region: "Europe",
    currency: { code: "MDL", name: "Moldovan leu", symbol: "L" },
    language: { code: "ro", name: "Romanian" },
    flag: "https://flagcdn.com/md.svg",
  },
  {
    name: "Monaco",
    code: "MC",
    capital: "Monaco",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/mc.svg",
  },
  {
    name: "Mongolia",
    code: "MN",
    capital: "Ulaanbaatar",
    region: "Asia",
    currency: { code: "MNT", name: "Mongolian tögrög", symbol: "₮" },
    language: { code: "mn", name: "Mongolian" },
    flag: "https://flagcdn.com/mn.svg",
  },
  {
    name: "Montenegro",
    code: "ME",
    capital: "Podgorica",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "sr", name: "Serbian" },
    flag: "https://flagcdn.com/me.svg",
  },
  {
    name: "Morocco",
    code: "MA",
    capital: "Rabat",
    region: "Africa",
    currency: { code: "MAD", name: "Moroccan dirham", symbol: "د.م." },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/ma.svg",
  },
  {
    name: "Mozambique",
    code: "MZ",
    capital: "Maputo",
    region: "Africa",
    currency: { code: "MZN", name: "Mozambican metical", symbol: "MT" },
    language: { code: "pt", name: "Portuguese" },
    flag: "https://flagcdn.com/mz.svg",
  },
  {
    name: "Myanmar",
    code: "MM",
    capital: "Naypyidaw",
    region: "Asia",
    currency: { code: "MMK", name: "Burmese kyat", symbol: "Ks" },
    language: { code: "my", name: "Burmese" },
    flag: "https://flagcdn.com/mm.svg",
  },
  {
    name: "Namibia",
    code: "NA",
    capital: "Windhoek",
    region: "Africa",
    currency: { code: "NAD", name: "Namibian dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/na.svg",
  },
  {
    name: "Nauru",
    code: "NR",
    capital: "Yaren",
    region: "Oceania",
    currency: { code: "AUD", name: "Australian dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/nr.svg",
  },
  {
    name: "Nepal",
    code: "NP",
    capital: "Kathmandu",
    region: "Asia",
    currency: { code: "NPR", name: "Nepalese rupee", symbol: "₨" },
    language: { code: "ne", name: "Nepali" },
    flag: "https://flagcdn.com/np.svg",
  },
  {
    name: "Netherlands",
    code: "NL",
    capital: "Amsterdam",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "nl", name: "Dutch" },
    flag: "https://flagcdn.com/nl.svg",
  },
  {
    name: "New Zealand",
    code: "NZ",
    capital: "Wellington",
    region: "Oceania",
    currency: { code: "NZD", name: "New Zealand dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/nz.svg",
  },
  {
    name: "Nicaragua",
    code: "NI",
    capital: "Managua",
    region: "Americas",
    currency: { code: "NIO", name: "Nicaraguan córdoba", symbol: "C$" },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/ni.svg",
  },
  {
    name: "Niger",
    code: "NE",
    capital: "Niamey",
    region: "Africa",
    currency: { code: "XOF", name: "West African CFA franc", symbol: "Fr" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/ne.svg",
  },
  {
    name: "Nigeria",
    code: "NG",
    capital: "Abuja",
    region: "Africa",
    currency: { code: "NGN", name: "Nigerian naira", symbol: "₦" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/ng.svg",
  },
  {
    name: "North Korea",
    code: "KP",
    capital: "Pyongyang",
    region: "Asia",
    currency: { code: "KPW", name: "North Korean won", symbol: "₩" },
    language: { code: "ko", name: "Korean" },
    flag: "https://flagcdn.com/kp.svg",
  },
  {
    name: "North Macedonia",
    code: "MK",
    capital: "Skopje",
    region: "Europe",
    currency: { code: "MKD", name: "Macedonian denar", symbol: "ден" },
    language: { code: "mk", name: "Macedonian" },
    flag: "https://flagcdn.com/mk.svg",
  },
  {
    name: "Norway",
    code: "NO",
    capital: "Oslo",
    region: "Europe",
    currency: { code: "NOK", name: "Norwegian krone", symbol: "kr" },
    language: { code: "no", name: "Norwegian" },
    flag: "https://flagcdn.com/no.svg",
  },
  {
    name: "Oman",
    code: "OM",
    capital: "Muscat",
    region: "Asia",
    currency: { code: "OMR", name: "Omani rial", symbol: "ر.ع." },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/om.svg",
  },
  {
    name: "Pakistan",
    code: "PK",
    capital: "Islamabad",
    region: "Asia",
    currency: { code: "PKR", name: "Pakistani rupee", symbol: "₨" },
    language: { code: "ur", name: "Urdu" },
    flag: "https://flagcdn.com/pk.svg",
  },
  {
    name: "Palau",
    code: "PW",
    capital: "Ngerulmud",
    region: "Oceania",
    currency: { code: "USD", name: "United States dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/pw.svg",
  },
  {
    name: "Panama",
    code: "PA",
    capital: "Panama City",
    region: "Americas",
    currency: { code: "PAB", name: "Panamanian balboa", symbol: "B/." },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/pa.svg",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    capital: "Port Moresby",
    region: "Oceania",
    currency: { code: "PGK", name: "Papua New Guinean kina", symbol: "K" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/pg.svg",
  },
  {
    name: "Paraguay",
    code: "PY",
    capital: "Asunción",
    region: "Americas",
    currency: { code: "PYG", name: "Paraguayan guaraní", symbol: "₲" },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/py.svg",
  },
  {
    name: "Peru",
    code: "PE",
    capital: "Lima",
    region: "Americas",
    currency: { code: "PEN", name: "Peruvian sol", symbol: "S/." },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/pe.svg",
  },
  {
    name: "Philippines",
    code: "PH",
    capital: "Quezon City",
    region: "Asia",
    currency: { code: "PHP", name: "Philippine peso", symbol: "₱" },
    language: { code: "tl", name: "Tagalog" },
    flag: "https://flagcdn.com/ph.svg",
  },
  {
    name: "Poland",
    code: "PL",
    capital: "Warsaw",
    region: "Europe",
    currency: { code: "PLN", name: "Polish złoty", symbol: "zł" },
    language: { code: "pl", name: "Polish" },
    flag: "https://flagcdn.com/pl.svg",
  },
  {
    name: "Portugal",
    code: "PT",
    capital: "Lisbon",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "pt", name: "Portuguese" },
    flag: "https://flagcdn.com/pt.svg",
  },
  {
    name: "Qatar",
    code: "QA",
    capital: "Doha",
    region: "Asia",
    currency: { code: "QAR", name: "Qatari riyal", symbol: "ر.ق" },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/qa.svg",
  },
  {
    name: "Republic of the Congo",
    code: "CG",
    capital: "Brazzaville",
    region: "Africa",
    currency: { code: "XAF", name: "Central African CFA franc", symbol: "Fr" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/cg.svg",
  },
  {
    name: "Romania",
    code: "RO",
    capital: "Bucharest",
    region: "Europe",
    currency: { code: "RON", name: "Romanian leu", symbol: "lei" },
    language: { code: "ro", name: "Romanian" },
    flag: "https://flagcdn.com/ro.svg",
  },
  {
    name: "Russia",
    code: "RU",
    capital: "Moscow",
    region: "Europe",
    currency: { code: "RUB", name: "Russian ruble", symbol: "₽" },
    language: { code: "ru", name: "Russian" },
    flag: "https://flagcdn.com/ru.svg",
  },
  {
    name: "Rwanda",
    code: "RW",
    capital: "Kigali",
    region: "Africa",
    currency: { code: "RWF", name: "Rwandan franc", symbol: "Fr" },
    language: { code: "rw", name: "Kinyarwanda" },
    flag: "https://flagcdn.com/rw.svg",
  },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    capital: "Basseterre",
    region: "Americas",
    currency: { code: "XCD", name: "East Caribbean dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/kn.svg",
  },
  {
    name: "Saint Lucia",
    code: "LC",
    capital: "Castries",
    region: "Americas",
    currency: { code: "XCD", name: "East Caribbean dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/lc.svg",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    capital: "Kingstown",
    region: "Americas",
    currency: { code: "XCD", name: "East Caribbean dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/vc.svg",
  },
  {
    name: "Samoa",
    code: "WS",
    capital: "Apia",
    region: "Oceania",
    currency: { code: "WST", name: "Samoan tālā", symbol: "T" },
    language: { code: "sm", name: "Samoan" },
    flag: "https://flagcdn.com/ws.svg",
  },
  {
    name: "San Marino",
    code: "SM",
    capital: "San Marino",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "it", name: "Italian" },
    flag: "https://flagcdn.com/sm.svg",
  },
  {
    name: "São Tomé and Príncipe",
    code: "ST",
    capital: "São Tomé",
    region: "Africa",
    currency: {
      code: "STN",
      name: "São Tomé and Príncipe dobra",
      symbol: "Db",
    },
    language: { code: "pt", name: "Portuguese" },
    flag: "https://flagcdn.com/st.svg",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    capital: "Riyadh",
    region: "Asia",
    currency: { code: "SAR", name: "Saudi riyal", symbol: "ر.س" },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/sa.svg",
  },
  {
    name: "Senegal",
    code: "SN",
    capital: "Dakar",
    region: "Africa",
    currency: { code: "XOF", name: "West African CFA franc", symbol: "Fr" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/sn.svg",
  },
  {
    name: "Serbia",
    code: "RS",
    capital: "Belgrade",
    region: "Europe",
    currency: { code: "RSD", name: "Serbian dinar", symbol: "дин." },
    language: { code: "sr", name: "Serbian" },
    flag: "https://flagcdn.com/rs.svg",
  },
  {
    name: "Seychelles",
    code: "SC",
    capital: "Victoria",
    region: "Africa",
    currency: { code: "SCR", name: "Seychellois rupee", symbol: "₨" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/sc.svg",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    capital: "Freetown",
    region: "Africa",
    currency: { code: "SLL", name: "Sierra Leonean leone", symbol: "Le" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/sl.svg",
  },
  {
    name: "Singapore",
    code: "SG",
    capital: "Singapore",
    region: "Asia",
    currency: { code: "SGD", name: "Singapore dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/sg.svg",
  },
  {
    name: "Slovakia",
    code: "SK",
    capital: "Bratislava",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "sk", name: "Slovak" },
    flag: "https://flagcdn.com/sk.svg",
  },
  {
    name: "Slovenia",
    code: "SI",
    capital: "Ljubljana",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "sl", name: "Slovenian" },
    flag: "https://flagcdn.com/si.svg",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    capital: "Honiara",
    region: "Oceania",
    currency: { code: "SBD", name: "Solomon Islands dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/sb.svg",
  },
  {
    name: "Somalia",
    code: "SO",
    capital: "Mogadishu",
    region: "Africa",
    currency: { code: "SOS", name: "Somali shilling", symbol: "Sh" },
    language: { code: "so", name: "Somali" },
    flag: "https://flagcdn.com/so.svg",
  },
  {
    name: "South Africa",
    code: "ZA",
    capital: "Pretoria",
    region: "Africa",
    currency: { code: "ZAR", name: "South African rand", symbol: "R" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/za.svg",
  },
  {
    name: "South Korea",
    code: "KR",
    capital: "Seoul",
    region: "Asia",
    currency: { code: "KRW", name: "South Korean won", symbol: "₩" },
    language: { code: "ko", name: "Korean" },
    flag: "https://flagcdn.com/kr.svg",
  },
  {
    name: "South Sudan",
    code: "SS",
    capital: "Juba",
    region: "Africa",
    currency: { code: "SSP", name: "South Sudanese pound", symbol: "£" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/ss.svg",
  },
  {
    name: "Spain",
    code: "ES",
    capital: "Madrid",
    region: "Europe",
    currency: { code: "EUR", name: "Euro", symbol: "€" },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/es.svg",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    capital: "Colombo",
    region: "Asia",
    currency: { code: "LKR", name: "Sri Lankan rupee", symbol: "₨" },
    language: { code: "si", name: "Sinhala" },
    flag: "https://flagcdn.com/lk.svg",
  },
  {
    name: "Sudan",
    code: "SD",
    capital: "Khartoum",
    region: "Africa",
    currency: { code: "SDG", name: "Sudanese pound", symbol: "£" },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/sd.svg",
  },
  {
    name: "Suriname",
    code: "SR",
    capital: "Paramaribo",
    region: "Americas",
    currency: { code: "SRD", name: "Surinamese dollar", symbol: "$" },
    language: { code: "nl", name: "Dutch" },
    flag: "https://flagcdn.com/sr.svg",
  },
  {
    name: "Sweden",
    code: "SE",
    capital: "Stockholm",
    region: "Europe",
    currency: { code: "SEK", name: "Swedish krona", symbol: "kr" },
    language: { code: "sv", name: "Swedish" },
    flag: "https://flagcdn.com/se.svg",
  },
  {
    name: "Switzerland",
    code: "CH",
    capital: "Bern",
    region: "Europe",
    currency: { code: "CHF", name: "Swiss franc", symbol: "Fr" },
    language: { code: "de", name: "German" },
    flag: "https://flagcdn.com/ch.svg",
  },
  {
    name: "Syria",
    code: "SY",
    capital: "Damascus",
    region: "Asia",
    currency: { code: "SYP", name: "Syrian pound", symbol: "£" },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/sy.svg",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    capital: "Dushanbe",
    region: "Asia",
    currency: { code: "TJS", name: "Tajikistani somoni", symbol: "SM" },
    language: { code: "tg", name: "Tajik" },
    flag: "https://flagcdn.com/tj.svg",
  },
  {
    name: "Tanzania",
    code: "TZ",
    capital: "Dodoma",
    region: "Africa",
    currency: { code: "TZS", name: "Tanzanian shilling", symbol: "Sh" },
    language: { code: "sw", name: "Swahili" },
    flag: "https://flagcdn.com/tz.svg",
  },
  {
    name: "Thailand",
    code: "TH",
    capital: "Bangkok",
    region: "Asia",
    currency: { code: "THB", name: "Thai baht", symbol: "฿" },
    language: { code: "th", name: "Thai" },
    flag: "https://flagcdn.com/th.svg",
  },
  {
    name: "Togo",
    code: "TG",
    capital: "Lomé",
    region: "Africa",
    currency: { code: "XOF", name: "West African CFA franc", symbol: "Fr" },
    language: { code: "fr", name: "French" },
    flag: "https://flagcdn.com/tg.svg",
  },
  {
    name: "Tonga",
    code: "TO",
    capital: "Nuku'alofa",
    region: "Oceania",
    currency: { code: "TOP", name: "Tongan paʻanga", symbol: "T$" },
    language: { code: "to", name: "Tongan" },
    flag: "https://flagcdn.com/to.svg",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    capital: "Port of Spain",
    region: "Americas",
    currency: { code: "TTD", name: "Trinidad and Tobago dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/tt.svg",
  },
  {
    name: "Tunisia",
    code: "TN",
    capital: "Tunis",
    region: "Africa",
    currency: { code: "TND", name: "Tunisian dinar", symbol: "د.ت" },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/tn.svg",
  },
  {
    name: "Turkey",
    code: "TR",
    capital: "Ankara",
    region: "Asia",
    currency: { code: "TRY", name: "Turkish lira", symbol: "₺" },
    language: { code: "tr", name: "Turkish" },
    flag: "https://flagcdn.com/tr.svg",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    capital: "Ashgabat",
    region: "Asia",
    currency: { code: "TMT", name: "Turkmenistan manat", symbol: "m" },
    language: { code: "tk", name: "Turkmen" },
    flag: "https://flagcdn.com/tm.svg",
  },
  {
    name: "Tuvalu",
    code: "TV",
    capital: "Funafuti",
    region: "Oceania",
    currency: { code: "AUD", name: "Australian dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/tv.svg",
  },
  {
    name: "Uganda",
    code: "UG",
    capital: "Kampala",
    region: "Africa",
    currency: { code: "UGX", name: "Ugandan shilling", symbol: "Sh" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/ug.svg",
  },
  {
    name: "Ukraine",
    code: "UA",
    capital: "Kyiv",
    region: "Europe",
    currency: { code: "UAH", name: "Ukrainian hryvnia", symbol: "₴" },
    language: { code: "uk", name: "Ukrainian" },
    flag: "https://flagcdn.com/ua.svg",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    capital: "Abu Dhabi",
    region: "Asia",
    currency: {
      code: "AED",
      name: "United Arab Emirates dirham",
      symbol: "د.إ",
    },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/ae.svg",
  },
  {
    name: "United Kingdom",
    code: "GB",
    capital: "London",
    region: "Europe",
    currency: { code: "GBP", name: "British pound", symbol: "£" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/gb.svg",
  },
  {
    name: "United States",
    code: "US",
    capital: "Washington, D.C.",
    region: "Americas",
    currency: { code: "USD", name: "United States dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/us.svg",
  },
  {
    name: "Uruguay",
    code: "UY",
    capital: "Montevideo",
    region: "Americas",
    currency: { code: "UYU", name: "Uruguayan peso", symbol: "$" },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/uy.svg",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    capital: "Tashkent",
    region: "Asia",
    currency: { code: "UZS", name: "Uzbekistani soʻm", symbol: "so'm" },
    language: { code: "uz", name: "Uzbek" },
    flag: "https://flagcdn.com/uz.svg",
  },
  {
    name: "Vanuatu",
    code: "VU",
    capital: "Port Vila",
    region: "Oceania",
    currency: { code: "VUV", name: "Vanuatu vatu", symbol: "Vt" },
    language: { code: "bi", name: "Bislama" },
    flag: "https://flagcdn.com/vu.svg",
  },
  {
    name: "Venezuela",
    code: "VE",
    capital: "Caracas",
    region: "Americas",
    currency: { code: "VES", name: "Venezuelan bolívar", symbol: "Bs.S." },
    language: { code: "es", name: "Spanish" },
    flag: "https://flagcdn.com/ve.svg",
  },
  {
    name: "Vietnam",
    code: "VN",
    capital: "Hanoi",
    region: "Asia",
    currency: { code: "VND", name: "Vietnamese đồng", symbol: "₫" },
    language: { code: "vi", name: "Vietnamese" },
    flag: "https://flagcdn.com/vn.svg",
  },
  {
    name: "Yemen",
    code: "YE",
    capital: "Sana'a",
    region: "Asia",
    currency: { code: "YER", name: "Yemeni rial", symbol: "﷼" },
    language: { code: "ar", name: "Arabic" },
    flag: "https://flagcdn.com/ye.svg",
  },
  {
    name: "Zambia",
    code: "ZM",
    capital: "Lusaka",
    region: "Africa",
    currency: { code: "ZMW", name: "Zambian kwacha", symbol: "ZK" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/zm.svg",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    capital: "Harare",
    region: "Africa",
    currency: { code: "ZWL", name: "Zimbabwean dollar", symbol: "$" },
    language: { code: "en", name: "English" },
    flag: "https://flagcdn.com/zw.svg",
  },
];
